### ISSUE TITLE
Can't resolve fcm.googleapis.com

### ISSUE THREAD

**Issue by Mik-chan** [web-push-libs/web-push-csharp#37]
While running sendNotificationMethod I get exception
```
System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
 at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at WebPush.WebPushClient.SendNotification(PushSubscription subscription, String payload, VapidDetails vapidDetails)
   at iResort.App_Code.WebPushWrapper.<>c__DisplayClass9_0.<Notify>b__0(String data) in C:\Users\sezer.yilmaz\source\repos\iResort\iResort\App_Code\WebPushWrapper.cs:line 92
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at iResort.App_Code.WebPushWrapper.Notify(Int32 id, String topic, String message, String url, String icon) in C:\Users\sezer.yilmaz\source\repos\iResort\iResort\App_Code\WebPushWrapper.cs:line 83
   at iResort.app.testNotification.Page_Load(Object sender, EventArgs e) in C:\Users\sezer.yilmaz\source\repos\iResort\iResort\app\testNotification.aspx.cs:line 17
   at System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Inner Exception 1: HttpRequestException: An error occurred while sending the request. 
Inner Exception 2: WebException: The remote name could not be resolved: 'fcm.googleapis.com'
```

And have no any idea why it happens. Can you help me?

**Comment by KathirveluM** [comment]
Same issue .  Any suggestions?

**Comment by coryjthompson** [comment]
Check your internet connection and that DNS is being resolved correctly.

It looks as if the DNS cannot be resolved. 

You can check with:
nslookup fcm.googleapis.com

**Comment by zx1986** [comment]
sometimes, nslookup fcm.googleapis.com response with an IPv6 address.
